Feat/issue 272
styxlab/gatsby-theme-try-ghost pull request #273
Opened 2021-05-31 19:04 UTC by chancharles

TBH, after reading more code, I think this PR doesn't really fit the intention of this module. 

I think it should be the consumer's responsibility to adjust its GraphQL to limit what should is used for the theme. However, this is not easily achievable with the Gatsby GraphQL setup (at least, not with my level of understanding). So, for my immediate need, I am just hacking at the source. Feel free to decline this PR if you find it too hacky.

2021-06-01 14:48 UTC, styxlab commented
I am generally in favor of this feature. As the source plugin can be viewed as a standalone package making it more flexible is a great idea. I can approve this change after the following changes/additions have been made:

1. Document the new option in the README of this package
2. Make the code backward compatible (if one does not have the new option in the config, code should not crash)
3. Please remove the ability to filter the "settings". I find this too dangerous as some fields are required. Alternatively, make sure required fields cannot be filtered away.

Thanks a lot for this contribution :-)

2021-06-02 13:31 UTC, chancharles commented
Great. Let's discuss the API of this option. Are you okay with this?

```
fetchOptions: {
  post: {
    filter: (post) => boolean
  },
  page: {
    filter: (page) => boolean
  },
  setting: {
    map: (setting) => setting
  }
}
```

2021-06-02 13:40 UTC, styxlab commented
I would prefer it simpler:
```
filter: {
  posts: (post) => boolean,
  pages: (page) => boolean
} 
```
And not support filtering the settings, unless you bring very good reasons for it.

2021-06-02 22:23 UTC, chancharles commented
@styxlab Please review the PR again.

2021-06-02 22:50 UTC, styxlab commented on packages/gatsby-source-try-ghost/gatsby-node.js
> +const prefetchPostAndPageNodes = (existingNodes, sourceNodeFields, settings, filter) => {
what about making default explicit by `filter = null` ?

2021-06-02 22:52 UTC, styxlab commented on packages/gatsby-source-try-ghost/gatsby-node.js
> +        if (filter && filter.posts) {
1. Also check that filter.posts is indeed a function, e.g. typeof filer.posts === 'function'
2. Maybe remove curly brackets and do it as a one-liner (also in other occurrences)

2021-06-02 22:56 UTC, styxlab requested changes
Instead of what I suggest in the previous comments...

How about attaching a default function in case nothing is defined, eg filter = { posts : (post) => true, pages: (post) => true }

then you can always apply the filter and don't need the additional if statements.

2021-06-02 22:59 UTC, chancharles commented
I like the idea but I will get a complaint for `filter = { posts: (post) => true, pages: (page) => true })`:

'post' is declared but its value is never read.ts(6133)

2021-06-02 23:14 UTC, styxlab commented
> I like the idea but I will get a complaint for `filter = { posts: (post) => true, pages: (page) => true })`:
> 
> 'post' is declared but its value is never read.ts(6133)

 `filter = { posts: () => true, pages: () => true })` should do.

2021-06-02 23:26 UTC, chancharles commented
Alright. Please review again.

2021-06-02 23:35 UTC, styxlab commented on packages/gatsby-source-try-ghost/gatsby-node.js
> +        posts.filter(filter.posts).forEach(async (post) => {
This may work, but I would like to make it explicit. (same as in line 166)
```
posts.filter((post) => filter.posts(post))
```

2021-06-02 23:35 UTC, styxlab commented on packages/gatsby-source-try-ghost/gatsby-node.js
> +        pages.filter(filter.pages).forEach(async (page) => {
same here, make it explicit.

2021-06-02 23:37 UTC, styxlab requested changes
One last change: Please rename `filter` to `customFilter` otherwise code gets really confusing. sorry that I see this that late.

Otherwise I am really happy with it.

2021-06-02 23:53 UTC, styxlab commented
Maybe `posts.filter(filter.posts)` is fine, but please make it consistent in all places. With renaming it should look like:
`posts.filter(customFilter.posts)`

2021-06-03 00:13 UTC, styxlab commented on packages/gatsby-source-try-ghost/gatsby-node.js
> +        pages = pages.filter(page => filter.pages(page))
`posts.filter(filter.posts)` ?

2021-06-03 00:14 UTC, styxlab requested changes

2021-06-03 00:14 UTC, styxlab commented on packages/gatsby-source-try-ghost/gatsby-node.js
> +        posts = posts.filter(post => filter.posts(post))
`posts.filter(filter.posts)` ?

2021-06-03 01:14 UTC, chancharles commented
No problem. Please check again.

2021-06-03 06:25 UTC, styxlab approved these changes

2021-06-03 06:26 UTC, merged

2021-06-03 06:28 UTC, styxlab commented
Looks great! Thanks so much for improving this package 💙

2021-06-03 10:34 UTC, chancharles commented
Thanks for your time!